%YAML:1.0
dataset_dir: /home/feiyu/Documents/Projects/2018-winter/EECS432_CV_VO/data/dataset_images_matlab

# ===== Settings for displaying
MAX_NUM_IMAGES: 300
PCL_WAIT_FOR_KEY_PRESS: "false" # If true, PCL Viewer will stop and wait for any of your keypress before continueing.

# ===== Save/Load trajectory
DRAW_GROUND_TRUTH_TRAJ: "true" # Ground truth traj's color is set as green. Estimated is set as white.

GROUND_TRUTH_TRAJ_FILENAME: /home/feiyu/Documents/Projects/2018-winter/EECS432_CV_VO/data/test_data/cam_traj_truth.txt
# Format of ground-truth data:
# In each row, there are 12 numbers representing the transformation matrix T=[R|t].
# Order of the 12 numbers: tx, ty, tz, R[:,0], R[:,1], R[:,2]
# Or say: T[0,3], T[1,3], T[2,3], T[0,0],T[1,0],T[2,0],T[0,1],T[1,1],T[2,1],T[0,2],T[1,2],T[2,2]
# See this "readPoseFromFile" in "io.cpp" for more details.

FILENAME_FOR_RESULT_TRAJECTORY: /home/feiyu/Documents/Projects/2018-winter/EECS432_CV_VO/data/test_data/cam_traj.txt

# ===== Dataset and camera intrinsics

# -- fr1_desk dataset
# https://vision.in.tum.de/data/datasets/rgbd-dataset/file_formats
# dataset_dir: /home/feiyu/Documents/Projects/EECS432_CV_VO/data/dataset_images_fr1_desk
# num_images: 100
# camera_info.fx: 517.3
# camera_info.fy: 516.5
# camera_info.cx: 325.1
# camera_info.cy: 249.7

# -- fr1_xyz dataset
# dataset_dir: /home/feiyu/Documents/Projects/EECS432_CV_VO/data/dataset_images_fr1_xyz
# num_images: 100
# camera_info.fx: 517.3
# camera_info.fy: 516.5
# camera_info.cx: 325.1
# camera_info.cy: 249.7

# -- New Tsukuba Stereo dataset used in matlab tutorial
num_images: 150
camera_info.fx: 615
camera_info.fy: 615
camera_info.cx: 320
camera_info.cy: 240

# ======================== VO Parameters ========================

# ------------------- Feature Matching -------------------

# Matching descriptos
feature_match_method_index: 1
  # method 1: the method in Dr. Xiang Gao's slambook:
  #           distance_threshold = max<float>(min_dis * match_ratio, 30.0);
  # method 2: the method in Lowe's 2004 paper:
  #           min dis / second min dis < 0.8
match_ratio: 2 # This is for method 1 used in Dr. Xiang Gao's slambook:
lowe_dist_ratio: 0.8 # This is for method 2 of Lowe's 2004 SIFT paper

# remove wrong matches
GRID_SIZE: 16
MAX_PTS_IN_GRID: 8

# ORB settings 
number_of_keypoints_to_extract: 10000
max_number_of_keypoints: 1500
scale_factor: 1.2
level_pyramid: 4
score_threshold: 20

# ------------------- Triangulation -------------------
min_triang_angle: 0.8
max_ratio_between_max_angle_and_median_angle: 20

# ------------------- Initialization -------------------

# 2 criterias for initializing VO
min_pixel_dist: 50
min_median_triangulation_angle: 2.0

# ------------------- Tracking -------------------
MIN_DIST_BETWEEN_KEYFRAME: 0.08
MIN_ROTATED_ANGLE: 0.08

# ------------------- Optimization -------------------
USE_BA: "true"                 # Use bundle adjustment for camera and points in single frame. 1 for true, 0 for false
MAX_NUM_FRAMES_FOR_BA: 5      # <= 20. I set the "BUFF_SIZE" in "vo.h" as 20, so only previous 20 frames are stored.
information_matrix: "1.0 0.0 0.0 1.0"
FIX_MAP_PTS: "true" # TO DEBUG: If I set it to true and optimize both camera pose and map points, there is huge error.
# UPDATE_MAP_PTS: "" # This equals (!FIX_MAP_PTS) by default