%YAML:1.0

# Path to the images
dataset_dir: /home/feiyu/Desktop/slam/code/project/0.5/dataset_images

# Camera intrinsics
# fr1 dataset
camera_info.fx: 517.3
camera_info.fy: 516.5
camera_info.cx: 325.1
camera_info.cy: 249.7

# ------------------------ VO Parameters ------------------------ 

# Matching descriptos
match_ratio: 2.0 # threshold_dis = (min_dis*2, 30)

# ORB settings 
number_of_features: 500
scale_factor: 1.2
level_pyramid: 4

# max_num_lost: 10
# min_inliers: 30
# keyframe_rotation: 0.1
# keyframe_translation: 0.1
# map_point_erase_ratio: 0.1