%YAML:1.0

# Path to the images
dataset_dir: /home/feiyu/Desktop/slam/code/project/0.5/dataset_images

# Camera intrinsics
# fr1 dataset
camera_info.fx: 517.3
camera_info.fy: 516.5
camera_info.cx: 325.1
camera_info.cy: 249.7
